### ISSUE TITLE
Duplicate "member" layer in LayerSwitcher for IWC & ICCAT

### ISSUE THREAD

**Issue by eblondel** [openfigis/FigisMap#39]
http://www.fao.org/figis/geoserver/factsheets/rfbs.html?rfb=IWC&extent=-142.3828125,-96.6796875,142.3828125,96.6796875&center=0,0&zoom=0&prj=4326 Even more weird that country lists filtered are not the same @marcobalestra any idea?

**Comment by eblondel** [comment]
@marcobalestra could you have a look to the `FigisMap.parser.countries` function.

``` javascript
p[ layerType ] = FigisMap.parser.layers( p[ layerType ] );
if ( ! p[ layerType ] ) p[ layerType ] = new Array();
p[ layerType ].push( newLayer );
p[ layerType ] = FigisMap.parser.layers( p[ layerType ], { type : layerType } );
```

The last line is the one that introduces the duplicated layers. But looking into `FigisMap.parser.layers`:

``` javascript
var ls = new Array();
    for ( var i = 0; i < obj.length; i++ ) {
        var l = FigisMap.parser.layer( obj[i], setProperties );
        if ( l.filter && l.filter.length > 150 && l.filter.indexOf(' OR ') > 0 ) {
            var fs = l.filter.split(' OR ');
            while ( fs.length > 0 ) {
                var newfs = fs.splice(0,50);
                var nl = new Object();
                for ( var p in l ) nl[p] = l[p];
                nl.filter = newfs.join(' OR ');
                if ( ls[0] ) nl.skipLegend = true;
                ls.push( nl );
            }
        } else {
            ls.push( l );
        }
    }

    return ls;
```

indeed they are rules that for a certain filter length, the filter will be splited into chunks, and then leading to create an array of length 2 for `pars.associated`.. then 2 distinct layers for "Members"... I thought you may shed light on this (it seems to be a patch, but i'm not aware of the reasons/background). In this piece of code, you see that in case of chunking, legend is skipped for the additional chunks, but the problem is that we keep adding 2 distinct country layers, visible to the layerswitcher.

I also noticed that we have the same code in the OL2 FigisMap.

This occurs mainly for IWC, this issue might have been hidden if IWC wasn't part of the initial list of RFBs configured in the viewer. @fabio2111 do you confirm?

**Comment by marcobalestra** [comment]
AFAIR it was introduced because sometimes in "OR" filters filter entries occurred more than once.

**Comment by marcobalestra** [comment]
Now I remember it... The issue: when filter becomes too long the URL invoking the layer breaks, because there are limits to URL length, and such limits apply to the browser, to FAO front-end proxy, to FI reverse proxy, to Geoserver websers and to Geoserver parsing code.
Initially this map http://www.fao.org/figis/geoserver/factsheets/rfbs.html?rfb=IWC contained this error, and country members were not displayed at all because of URL length.
It's impossibile for us to fix proxies and users browsers.
I found this workaround: in case "OR" filter contains too many entries, so many that URL length becomes risky, then the layer is duplicated, in chunks with a maximum of 50 entries.
I warned since the very beginning that in these particular cases the layer is duplicated, also in legend, and we all were aware of it - but it's better to have occasionally a layer duplication in Legend rather than an error.

**Comment by eblondel** [comment]
now that i think in, can't we try, for the country filtering, to use a CQL 'IN' filter (supported by Geoserver) instead of a sequence of 'OR'? it will reduce the length of the filter, but i don't know if it would reduce enough the url length

`
property IN('value1','value2',...,'valueN')
`
instead of
`
property = 'value1' OR property = 'value2' OR .... OR property = 'valueN'`
`

**Comment by eblondel** [comment]
Example of cql_filter
 http://www.fao.org/figis/geoserver/fifao/wms?service=WMS&version=1.1.0&request=GetMap&layers=fifao:country_bounds&styles=&bbox=-180.0,-90.0,90.0,180.0&width=660&height=330&srs=EPSG:4326&format=application/openlayers&cql_filter=ISO_3 IN('FRA','ITA')

**Comment by marcobalestra** [comment]
List is generated dynamically, it would be a consistent effort and would lead to a limited result (wouldn't reduce very much length, mainly due to non-alphanumeric characters web encoding).
In addition it wouldn't grant that filter length doesn't exceed, and would make harder to fix it like we do with "OR" sequence.

**Comment by eblondel** [comment]
agreed, you are right.
